import "katex/dist/katex.min.css";
import "highlight.js/styles/github-dark.min.css";
import "@/styles/markdown.css";

import React from "react";
import { renderMarkdown, type TocEntry } from "@/lib/markdown";
import { ReadingProgress } from "@/components/blog/ReadingProgress";

interface MarkdownRendererProps {
  content: string;
  /** Blog slug – enables reading-progress bar + view/like counters. */
  slug?: string;
}

/**
 * Server component that renders markdown via the unified pipeline and
 * optionally shows a reading-progress bar with reading time + counters.
 */
export async function MarkdownRenderer({ content, slug }: MarkdownRendererProps) {
  if (!content?.trim()) return null;
  const { html, wordCount } = await renderMarkdown(content);
  return (
    <>
      {slug && <ReadingProgress wordCount={wordCount} slug={slug} />}
      <article
        className="markdown-body"
        // HTML is generated by our own unified pipeline from trusted local vault markdown
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </>
  );
}

/**
 * Standalone helper for callers that need the ToC/wordCount without
 * the full React component (e.g. for TableOfContents sidebars).
 */
export { renderMarkdown, type TocEntry };
