import "katex/dist/katex.min.css";
import "highlight.js/styles/github-dark.min.css";
import "@/styles/markdown.css";

import React from "react";
import { renderMarkdown, type TocEntry } from "@/lib/markdown";
import { ReadingProgress } from "@/components/blog/ReadingProgress";

interface MarkdownRendererProps {
  content: string;
  /** Blog slug – enables reading-progress bar + view/like counters. */
  slug?: string;
}

interface MarkdownRenderResult {
  element: React.ReactElement;
  toc: TocEntry[];
}

/**
 * Server component that renders markdown via the unified pipeline and
 * optionally shows a reading-progress bar with reading time + counters.
 * Returns both the rendered JSX element and the ToC data.
 */
export async function renderMarkdownWithToc({ content, slug }: MarkdownRendererProps): Promise<MarkdownRenderResult> {
  if (!content?.trim()) return { element: <></>, toc: [] };
  const { html, toc, wordCount } = await renderMarkdown(content);
  const element = (
    <>
      {slug && <ReadingProgress wordCount={wordCount} slug={slug} />}
      <article
        className="markdown-body"
        // HTML is generated by our own unified pipeline from trusted local vault markdown
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </>
  );
  return { element, toc };
}

/**
 * Original server component for backwards compatibility.
 * Renders markdown and discards ToC data.
 */
export async function MarkdownRenderer({ content, slug }: MarkdownRendererProps) {
  const { element } = await renderMarkdownWithToc({ content, slug });
  return element;
}

/**
 * Standalone helper for callers that need the ToC/wordCount without
 * the full React component (e.g. for TableOfContents sidebars).
 */
export { renderMarkdown, type TocEntry };
