name: Sync Content Dispatcher

on:
  repository_dispatch:
    types: [sync-content]
  workflow_dispatch:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Submodule Sync
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: update-submodule
